name: Basic Testing CI/CD

on:
  push:
    branches: [ speech_mode ]
  pull_request:
    branches: [ speech_mode ]

jobs:
  basic-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.12]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install core dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-ci.txt
        
    - name: Run Basic Tests
      run: |
        python -m pytest tests/unit/test_app_core.py::TestSecurityFunctions -v --tb=short
        python -m pytest tests/unit/test_memory_manager.py::TestMemoryStats -v --tb=short
        
    - name: Generate Coverage Report
      run: |
        python -m pytest tests/unit/test_app_core.py::TestSecurityFunctions --cov=app --cov-report=xml
        
    - name: Upload Coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
